### ISSUE TITLE
Request: Have attachTo finder return base object variable name in command.

### ISSUE THREAD

**Issue by Drofseh** [7erra/-Terra-s-Editing-Extensions#2]
Right now the attachTo finder (which is fantastic) returns this format when selecting Export Commands

`this attachTo [ClassName,[X,Y,Z]];`

It would be nice if the base object has a variable name that it could be used instead of the class name.
This would make it even faster as the code could be pasted directly without requiring any editing.

`this attachTo [varName,[X,Y,Z]];`

**Comment by 7erra** [comment]
Implemented with v2
