### ISSUE TITLE
Config Viewer 73: Search Bars Do Not Initiate List Updates

### ISSUE THREAD

**Issue by Ansible2** [7erra/-Terra-s-Editing-Extensions#36]
**Mods:**
- **Arma 3:** `2.00.146773 Stable`
- **Terras Editing Extensions:** `2.6` 

**Description:**
If a user types into the search bar, the corresponding list is not automatically updated with each keystroke. Applies to both the properties and class search bars.

**NOTE:** Updates to the properties list do take affect with other events such as changing to a new class or turning on or off _Inheritance_ or _Show Classes_

**Steps to reproduce:**
1. Open the viewer while in either a mission or the Eden Editor
2. Type Something into the class search bar
3. Select a class in the search bar
4. Type text into the properties search bar

**Expected behavior:**
- Each keystroke updates the list

**Actual behavior:**
- No updates initiate on the list when a user types into the field

**Comment by R3voA3** [comment]
Confirmed

**Comment by Ansible2** [comment]
https://github.com/7erra/Terra-s-Editing-Extensions/blob/9391d7012f842fc29db48e9397171e8744cd4339/TER_editing/gui/scripts/TER_3den_RscDisplayConfigViewer73.sqf#L66
https://github.com/7erra/Terra-s-Editing-Extensions/blob/9391d7012f842fc29db48e9397171e8744cd4339/TER_editing/gui/scripts/TER_3den_RscDisplayConfigViewer73.sqf#L122

@7erra 
Unsure if this was intended or the consequences of changing it, but wrapping these lines in:
`with uiNamespace do {/*code*/};`

As is standard with most other events, fixed the issue.

**Comment by 7erra** [comment]
> Unsure if this was intended or the consequences of changing it, but wrapping these lines in:
with uiNamespace do {/*code*/};
> 
> As is standard with most other events, fixed the issue.

@Ansible2 
Yeah that was the issue. I am trying to make more use of BIS_fnc_initDisplay so it is more streamlined with vanilla displays. This means that the ui scripts are compiled into the uiNamespace at game start. Has been fixed with 88e2050
